
spring.application.name=chat-app-backend

spring.data.mongodb.uri=mongodb+srv://gaganprajapati:NAYA_PASSWORD@chat-app.qixlhsy.mongodb.net/?appName=chat-app

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}

groq.api.key=${GROQ_API_KEY}