spring.application.name=chat-app-backend

spring.data.mongodb.uri=mongodb+srv://gaganprajapati:gagan%408960@chat-app.qixlhsy.mongodb.net/chatapp?retryWrites=true&w=majority

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB